### ISSUE TITLE
Wrong calculation

### ISSUE THREAD

**Issue by waymaker55** [ETHLend/Kogia#26]
Hello
The calculation for loan period, number/total  installments its not always accurate.

**Comment by waymaker55** [comment]
Even the calculation for installments size is off,its ether its a little bite higher or lower.

**Comment by waymaker55** [comment]
![img_20180406_093258](https://user-images.githubusercontent.com/38107153/38415426-04056592-3981-11e8-9a70-241b80f0a658.jpg)
![15230087787721415573265](https://user-images.githubusercontent.com/38107153/38415502-438e5728-3981-11e8-987c-917188dd71ab.jpg)

**Comment by waymaker55** [comment]
As at now 0.3 does not work on the Toshi Dapp , even when you try to access the site via the web browser on the Toshi app.
![screenshot_2018-04-06-10-06-19](https://user-images.githubusercontent.com/38107153/38415919-817b6cb4-3982-11e8-849a-71726973fb74.png)
![screenshot_2018-04-06-10-06-11](https://user-images.githubusercontent.com/38107153/38415933-8eed6e38-3982-11e8-926f-b8f845152b1b.png)

**Comment by shaneBen23** [comment]
Hi @waymaker55,
Thank you for pointing out the miss calculation we have already corrected these calculation issues.

**Comment by waymaker55** [comment]
Okay but I an still experiencing the miss calculation take for example the snapshot  I took today. Normally contribution distribution (days) its to run form 1-30 days but on the picture you can see the max is 10days making the total loan period incorrect.
![img_20180409_082830](https://user-images.githubusercontent.com/38107153/38502162-397181f0-3bfe-11e8-9982-715a3459144e.jpg)

**Comment by waymaker55** [comment]
And please you did not address the system not working on the Toshi Dapp

**Comment by vvville** [comment]
@waymaker55 Can you contact ETHLend through either Telegram or Gitter about the Bug Bounty? Thanks!
